#!/bin/bash

rm *.plt

# pkill -x gnuplot

make

./lm 0. 1.4 0.0001 0.62 10000 10050

#gnuplot -e "load 'Bifurcation'; pause mouse close"
#gnuplot -e "load 'Time-Domain'; pause mouse close"
#gnuplot -e "load 'First-Return-Map'; pause mouse close"
#mnuplot -e "load 'Second-Return-Map'; pause mouse close"
